set API_JWT_ALGORITHM_SECRET=notes-application-jwt-secret
set API_SECURITY_LOGIN_USERNAME=victor
set API_SECURITY_LOGIN_BCRYPT_PASSWORD=$2a$12$uxRyqtZ5VEe.H0raGm4aiekEjdctWZkXSpXO88czd1v/whhesBreG
mvnw clean package