spring.datasource.url=jdbc:mysql://localhost:3306/notesdb?ServerTimezone=UTC
spring.datasource.username=
spring.datasource.password=
server.port=${SERVER_PORT:4201}
api.jwt.algorithm.secret=${API_JWT_ALGORITHM_SECRET}
api.security.login.username=${API_SECURITY_LOGIN_USERNAME}
api.security.login.bcrypt.password=${API_SECURITY_LOGIN_BCRYPT_PASSWORD}